### ISSUE TITLE
Bug: action with the ID "Go To Last Tab" was already registered

### ISSUE THREAD

**Issue by AndKiel** [jiripospisil/idea-gototabs#8]
IDE: RubyMine 2020.1
Plugin version: 1.4

```
java.lang.Throwable: action with the ID "Go To Last Tab" was already registered. Action being registered is Go To Last Tab (null); Registered action is Go To Last Tab (null)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:400)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:389)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerChameleon(ActionManagerImpl.java:1244)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.addToMap(ActionManagerImpl.java:1217)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1188)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1180)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1255)
	at com.jpospisil.BackgroundPostStartupActivity.addAction(BackgroundPostStartupActivity.java:34)
	at com.jpospisil.BackgroundPostStartupActivity.addActions(BackgroundPostStartupActivity.java:23)
	at com.jpospisil.BackgroundPostStartupActivity.runActivity(BackgroundPostStartupActivity.java:16)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$null$5(StartupManagerImpl.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:257)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$scheduleBackgroundPostStartupActivities$6(StartupManagerImpl.java:438)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by jiripospisil** [comment]
How can I reproduce the issue? Did you get the error right after updating the plugin? Please consider uninstalling the plugin and use the now officially supported key bindings (Keymap -> Other -> Tabs).

**Comment by AndKiel** [comment]
It's possible I've been getting that error in the past but I didn't notice. I somehow missed that there are now officially supported key bindings for this. Removed the plug-in and switched to them, thanks. If it does not happen to you on the latest RubyMine, I'm not sure how to reproduce it. Possibly the issue can be closed as there are now official bindings for switching tabs.

**Comment by jiripospisil** [comment]
> I somehow missed that there are now officially supported key bindings for this. Removed the plug-in and switched to them, thanks.

I don't think they advertised that much maybe because their position from the very start was that it's not really needed.

> Possibly the issue can be closed as there are now official bindings for switching tabs.

Yeah, I think it's not worth the effort to dig into it. Everybody should just switch over. I appreciate the bug report though.
