### ISSUE TITLE
Action with the ID "Go To Last Tab" was already registered

### ISSUE THREAD

**Issue by tuckerritti** [jiripospisil/idea-gototabs#9]
I've been getting this error when I have more than one project open and launch webstorm, or when I have one project open and try to open another project in a new window.

```
java.lang.Throwable: action with the ID "Go To Last Tab" was already registered. Action being registered is Go To Last Tab (null); Registered action is Go To Last Tab (null)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:399)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:388)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerChameleon(ActionManagerImpl.java:1243)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.addToMap(ActionManagerImpl.java:1216)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1187)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1179)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1254)
	at com.jpospisil.BackgroundPostStartupActivity.addAction(BackgroundPostStartupActivity.java:34)
	at com.jpospisil.BackgroundPostStartupActivity.addActions(BackgroundPostStartupActivity.java:23)
	at com.jpospisil.BackgroundPostStartupActivity.runActivity(BackgroundPostStartupActivity.java:16)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$null$5(StartupManagerImpl.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:257)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$scheduleBackgroundPostStartupActivities$6(StartupManagerImpl.java:438)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by tuckerritti** [comment]
I was mistaken, It looks like this exception happens every time I open WebStorm.

**Comment by jiripospisil** [comment]
Hello, this plugin is deprecated. Please consider uninstalling it and use the now officially supported key bindings (Keymap -> Other -> Tabs).
